service: animal-api

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  stage: dev
  environment:
    DYNAMODB_TABLE: animal-table

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  include:
    - features/**
    - errorHandler.js

plugins:
  - serverless-offline

functions:
  getAllSpecies:
    handler: features/read.getAllSpecies
    events:
      - http:
          path: /animal
          method: get
  getSpecies:
    handler: features/read.getSpecies
    events:
      - http:
          path: /animal/{species}
          method: get
  addSpecies:
    handler: features/create.addSpecies
    events:
      - http:
          path: /animal
          method: post
